(DESIGNSIZE R 10.0)
(COMMENT DESIGNSIZE IS IN POINTS)
(COMMENT OTHER SIZES ARE MULTIPLES OF DESIGNSIZE)
(CHECKSUM O 2215053170)
(LIGTABLE
   (LABEL BOUNDARYCHAR)
   (LABEL C A)
   (LIG C A C B)
   (STOP)
   )
(CHARACTER C A
   (CHARWD R 0.5)
   (COMMENT
      (LIG C A C B)
      )
   )
(CHARACTER C B
   (CHARWD R 0.5)
   )
