//! Latin Modern Math (`latinmodern-math.otf`) OpenType `MATH` data, generated by
//! `tools/gen_lm_math.py`. Do not edit by hand.
//!
//! Provenance: `LatinModernMath-Regular`, SHA-256 `6075562b771f8b82f0c179e363389684f2dd09de30038269e2628e504bd7be0f`,
//! 733736 bytes, unitsPerEm 1000; the file the FT-018 font engine's README
//! lists (TeX Live 2026 `fonts/opentype/public/lm-math`). Values are font units
//! (percent fields in percent). `MathVariants` vertical variants are `(glyph id,
//! advance height)` pairs, smallest first, and assemblies are
//! `(glyph id, start connector, end connector, full advance, extender flag)`.
#![allow(clippy::unreadable_literal)]

use crate::metrics::OpenTypeMathConstants;

pub const UNITS_PER_EM: u16 = 1000;
/// `OS/2.sxHeight`: TeX's x_height (σ5) equivalent.
pub const X_HEIGHT: i16 = 431;
/// `OS/2.sCapHeight`.
pub const CAP_HEIGHT: i16 = 683;
/// Advance of U+2003 EM SPACE: TeX's quad (σ6) equivalent.
pub const QUAD: u16 = 1000;
pub const SCRIPT_PERCENT_SCALE_DOWN: i16 = 70;
pub const SCRIPT_SCRIPT_PERCENT_SCALE_DOWN: i16 = 50;
pub const DISPLAY_OPERATOR_MIN_HEIGHT: u16 = 1300;
pub const MIN_CONNECTOR_OVERLAP: u16 = 20;
/// Every `MathConstants` value the specification defines, in its order.
pub const ALL_CONSTANTS: &[(&str, i32)] = &[
    ("script_percent_scale_down", 70),
    ("script_script_percent_scale_down", 50),
    ("delimited_sub_formula_min_height", 1300),
    ("display_operator_min_height", 1300),
    ("math_leading", 154),
    ("axis_height", 250),
    ("accent_base_height", 450),
    ("flattened_accent_base_height", 664),
    ("subscript_shift_down", 247),
    ("subscript_top_max", 344),
    ("subscript_baseline_drop_min", 200),
    ("superscript_shift_up", 363),
    ("superscript_shift_up_cramped", 289),
    ("superscript_bottom_min", 108),
    ("superscript_baseline_drop_max", 250),
    ("sub_superscript_gap_min", 160),
    ("superscript_bottom_max_with_subscript", 344),
    ("space_after_script", 56),
    ("upper_limit_gap_min", 200),
    ("upper_limit_baseline_rise_min", 111),
    ("lower_limit_gap_min", 167),
    ("lower_limit_baseline_drop_min", 600),
    ("stack_top_shift_up", 444),
    ("stack_top_display_style_shift_up", 677),
    ("stack_bottom_shift_down", 345),
    ("stack_bottom_display_style_shift_down", 686),
    ("stack_gap_min", 120),
    ("stack_display_style_gap_min", 280),
    ("stretch_stack_top_shift_up", 111),
    ("stretch_stack_bottom_shift_down", 600),
    ("stretch_stack_gap_above_min", 200),
    ("stretch_stack_gap_below_min", 167),
    ("fraction_numerator_shift_up", 394),
    ("fraction_numerator_display_style_shift_up", 677),
    ("fraction_denominator_shift_down", 345),
    ("fraction_denominator_display_style_shift_down", 686),
    ("fraction_numerator_gap_min", 40),
    ("fraction_num_display_style_gap_min", 120),
    ("fraction_rule_thickness", 40),
    ("fraction_denominator_gap_min", 40),
    ("fraction_denom_display_style_gap_min", 120),
    ("skewed_fraction_horizontal_gap", 350),
    ("skewed_fraction_vertical_gap", 96),
    ("overbar_vertical_gap", 120),
    ("overbar_rule_thickness", 40),
    ("overbar_extra_ascender", 40),
    ("underbar_vertical_gap", 120),
    ("underbar_rule_thickness", 40),
    ("underbar_extra_ascender", 40),
    ("radical_vertical_gap", 50),
    ("radical_display_style_vertical_gap", 148),
    ("radical_rule_thickness", 40),
    ("radical_extra_ascender", 40),
    ("radical_kern_before_degree", 278),
    ("radical_kern_after_degree", -556),
    ("radical_degree_bottom_raise_percent", 60),
];

/// The subset `MathParams::from_opentype` consumes.
pub const CONSTANTS: OpenTypeMathConstants = OpenTypeMathConstants {
    units_per_em: 1000,
    axis_height: 250,
    fraction_numerator_display_style_shift_up: 677,
    fraction_numerator_shift_up: 394,
    stack_top_shift_up: 444,
    fraction_denominator_display_style_shift_down: 686,
    fraction_denominator_shift_down: 345,
    superscript_shift_up: 363,
    superscript_shift_up_cramped: 289,
    subscript_shift_down: 247,
    superscript_baseline_drop_max: 250,
    subscript_baseline_drop_min: 200,
    fraction_rule_thickness: 40,
    upper_limit_gap_min: 200,
    lower_limit_gap_min: 167,
    upper_limit_baseline_rise_min: 111,
    lower_limit_baseline_drop_min: 600,
    delimited_sub_formula_min_height: 1300,
};

/// A vertical variant list from `MathVariants` for one symbol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct VerticalVariants {
    pub ch: char,
    pub base_gid: u16,
    /// `(glyph id, advance height)`, smallest first.
    pub variants: &'static [(u16, u16)],
    /// `(glyph id, start connector, end connector, full advance, extender)`.
    pub assembly: &'static [(u16, u16, u16, u16, bool)],
}

pub static VERTICAL_VARIANTS: &[VerticalVariants] = &[
    VerticalVariants {
        ch: '\u{0028}',
        base_gid: 9,
        variants: &[(9, 997), (2367, 1095), (2389, 1195), (2411, 1445), (2433, 1793), (2455, 2093), (2477, 2393), (2499, 2991)],
        assembly: &[(2503, 0, 249, 1495, false), (2504, 498, 498, 498, true), (2505, 249, 0, 1495, false)],
    },
    VerticalVariants {
        ch: '\u{0029}',
        base_gid: 10,
        variants: &[(10, 997), (2368, 1095), (2390, 1195), (2412, 1445), (2434, 1793), (2456, 2093), (2478, 2393), (2500, 2991)],
        assembly: &[(2506, 0, 249, 1495, false), (2507, 498, 498, 498, true), (2508, 249, 0, 1495, false)],
    },
    VerticalVariants {
        ch: '\u{002F}',
        base_gid: 16,
        variants: &[(16, 1001), (2672, 1311), (2679, 1717), (2686, 2249), (2693, 2945), (2700, 3859), (2707, 5055), (2714, 6621)],
        assembly: &[],
    },
    VerticalVariants {
        ch: '\u{005B}',
        base_gid: 60,
        variants: &[(60, 1001), (2373, 1101), (2395, 1201), (2417, 1451), (2439, 1801), (2461, 2101), (2483, 2401), (2525, 3001)],
        assembly: &[(2527, 0, 500, 1500, false), (2528, 1000, 1000, 1000, true), (2529, 500, 0, 1500, false)],
    },
    VerticalVariants {
        ch: '\u{005C}',
        base_gid: 61,
        variants: &[(61, 1001), (2673, 1311), (2680, 1717), (2687, 2249), (2694, 2945), (2701, 3859), (2708, 5055), (2715, 6621)],
        assembly: &[],
    },
    VerticalVariants {
        ch: '\u{005D}',
        base_gid: 62,
        variants: &[(62, 1001), (2374, 1101), (2396, 1201), (2418, 1451), (2440, 1801), (2462, 2101), (2484, 2401), (2526, 3001)],
        assembly: &[(2530, 0, 500, 1500, false), (2531, 1000, 1000, 1000, true), (2532, 500, 0, 1500, false)],
    },
    VerticalVariants {
        ch: '\u{007B}',
        base_gid: 92,
        variants: &[(92, 1001), (2371, 1101), (2393, 1201), (2415, 1451), (2437, 1801), (2459, 2101), (2481, 2401), (2515, 3001)],
        assembly: &[(2517, 0, 374, 750, false), (2518, 748, 748, 748, true), (2519, 374, 374, 1500, false), (2518, 748, 748, 748, true), (2520, 374, 0, 750, false)],
    },
    VerticalVariants {
        ch: '\u{007C}',
        base_gid: 93,
        variants: &[(93, 1001), (2677, 1203), (2684, 1445), (2691, 1735), (2698, 2085), (2705, 2503), (2712, 3005), (2719, 3607)],
        assembly: &[(2721, 0, 601, 1202, false), (2722, 1202, 1202, 1202, true), (2723, 601, 0, 1202, false)],
    },
    VerticalVariants {
        ch: '\u{007D}',
        base_gid: 94,
        variants: &[(94, 1001), (2372, 1101), (2394, 1201), (2416, 1451), (2438, 1801), (2460, 2101), (2482, 2401), (2516, 3001)],
        assembly: &[(2521, 0, 374, 750, false), (2522, 748, 748, 748, true), (2523, 374, 374, 1500, false), (2522, 748, 748, 748, true), (2524, 374, 0, 750, false)],
    },
    VerticalVariants {
        ch: '\u{2016}',
        base_gid: 2727,
        variants: &[(2727, 1001), (2678, 1203), (2685, 1445), (2692, 1735), (2699, 2085), (2706, 2503), (2713, 3005), (2720, 3607)],
        assembly: &[(2724, 0, 601, 1202, false), (2725, 1202, 1202, 1202, true), (2726, 601, 0, 1202, false)],
    },
    VerticalVariants {
        ch: '\u{2191}',
        base_gid: 1867,
        variants: &[(1867, 883), (1869, 1349)],
        assembly: &[(1871, 0, 169, 506, false), (1872, 337, 337, 337, true), (1873, 169, 0, 505, false)],
    },
    VerticalVariants {
        ch: '\u{2193}',
        base_gid: 1868,
        variants: &[(1868, 883), (1870, 1349)],
        assembly: &[(1874, 0, 169, 505, false), (1875, 337, 337, 337, true), (1876, 169, 0, 506, false)],
    },
    VerticalVariants {
        ch: '\u{2195}',
        base_gid: 1894,
        variants: &[(1894, 1015), (1895, 1015)],
        assembly: &[(1896, 0, 127, 380, false), (1897, 254, 254, 254, true), (1898, 127, 0, 380, false)],
    },
    VerticalVariants {
        ch: '\u{220F}',
        base_gid: 3061,
        variants: &[(3061, 1001), (3075, 1401)],
        assembly: &[],
    },
    VerticalVariants {
        ch: '\u{2210}',
        base_gid: 3062,
        variants: &[(3062, 1001), (3076, 1401)],
        assembly: &[],
    },
    VerticalVariants {
        ch: '\u{2211}',
        base_gid: 3060,
        variants: &[(3060, 1001), (3074, 1401)],
        assembly: &[],
    },
    VerticalVariants {
        ch: '\u{221A}',
        base_gid: 3077,
        variants: &[(3077, 1001), (3081, 1201), (3082, 1801), (3083, 2401), (3084, 3001)],
        assembly: &[(3078, 0, 320, 1820, false), (3079, 640, 640, 640, true), (3080, 320, 0, 620, false)],
    },
    VerticalVariants {
        ch: '\u{222B}',
        base_gid: 3049,
        variants: &[(3049, 1112), (3063, 2223)],
        assembly: &[],
    },
    VerticalVariants {
        ch: '\u{222E}',
        base_gid: 3053,
        variants: &[(3053, 1112), (3067, 2223)],
        assembly: &[],
    },
    VerticalVariants {
        ch: '\u{22C0}',
        base_gid: 2771,
        variants: &[(2771, 1045), (2772, 1394)],
        assembly: &[],
    },
    VerticalVariants {
        ch: '\u{22C1}',
        base_gid: 2773,
        variants: &[(2773, 1045), (2774, 1394)],
        assembly: &[],
    },
    VerticalVariants {
        ch: '\u{22C2}',
        base_gid: 2765,
        variants: &[(2765, 1023), (2766, 1357)],
        assembly: &[],
    },
    VerticalVariants {
        ch: '\u{22C3}',
        base_gid: 2767,
        variants: &[(2767, 1023), (2768, 1357)],
        assembly: &[],
    },
    VerticalVariants {
        ch: '\u{2308}',
        base_gid: 2353,
        variants: &[(2353, 1001), (2375, 1101), (2397, 1201), (2419, 1451), (2441, 1801), (2463, 2101), (2485, 2401), (2533, 3001)],
        assembly: &[(2528, 1000, 1000, 1000, true), (2529, 500, 0, 1500, false)],
    },
    VerticalVariants {
        ch: '\u{2309}',
        base_gid: 2354,
        variants: &[(2354, 1001), (2376, 1101), (2398, 1201), (2420, 1451), (2442, 1801), (2464, 2101), (2486, 2401), (2534, 3001)],
        assembly: &[(2531, 1000, 1000, 1000, true), (2532, 500, 0, 1500, false)],
    },
    VerticalVariants {
        ch: '\u{230A}',
        base_gid: 2355,
        variants: &[(2355, 1001), (2377, 1101), (2399, 1201), (2421, 1451), (2443, 1801), (2465, 2101), (2487, 2401), (2535, 3001)],
        assembly: &[(2527, 0, 500, 1500, false), (2528, 1000, 1000, 1000, true)],
    },
    VerticalVariants {
        ch: '\u{230B}',
        base_gid: 2356,
        variants: &[(2356, 1001), (2378, 1101), (2400, 1201), (2422, 1451), (2444, 1801), (2466, 2101), (2488, 2401), (2536, 3001)],
        assembly: &[(2530, 0, 500, 1500, false), (2531, 1000, 1000, 1000, true)],
    },
    VerticalVariants {
        ch: '\u{27E8}',
        base_gid: 2579,
        variants: &[(2579, 1001), (2583, 1101), (2587, 1201), (2591, 1451), (2595, 1801), (2599, 2101), (2603, 2401), (2607, 3001)],
        assembly: &[],
    },
    VerticalVariants {
        ch: '\u{27E9}',
        base_gid: 2580,
        variants: &[(2580, 1001), (2584, 1101), (2588, 1201), (2592, 1451), (2596, 1801), (2600, 2101), (2604, 2401), (2608, 3001)],
        assembly: &[],
    },
    VerticalVariants {
        ch: '\u{2A00}',
        base_gid: 2802,
        variants: &[(2802, 987), (2803, 1305)],
        assembly: &[],
    },
    VerticalVariants {
        ch: '\u{2A01}',
        base_gid: 2806,
        variants: &[(2806, 987), (2807, 1305)],
        assembly: &[],
    },
    VerticalVariants {
        ch: '\u{2A02}',
        base_gid: 2811,
        variants: &[(2811, 987), (2812, 1305)],
        assembly: &[],
    },
];
