(DESIGNSIZE R 10.0)
(COMMENT DESIGNSIZE IS IN POINTS)
(COMMENT OTHER SIZES ARE MULTIPLES OF DESIGNSIZE)
(CHECKSUM O 2215053170)
(BOUNDARYCHAR O 372)
(LIGTABLE
   (LABEL C A)
   (/LIG> O 372 C B)
   (STOP)
   )
(CHARACTER C A
   (CHARWD R 0.5)
   (COMMENT
      (/LIG> O 372 C B)
      )
   )
(CHARACTER C B
   (CHARWD R 0.5)
   )
