#!/usr/bin/env python3
"""TikZ oracle harness: pdflatex (+tikz) vs flashtex-tikz-pdf at 150 dpi.

pdflatex is the ORACLE ONLY; it never runs in the product path.

For every fixture in fixtures/tikz/*.tex:
  1. pdflatex renders the reference PDF (standalone class, border=5pt).
  2. flashtex-tikz-pdf renders ours from the same source (no TeX involved).
  3. Ghostscript rasterises both at 150 dpi (ppmraw, 4-bit anti-aliasing
     for graphics and text).
  4. Pixel comparison (see METHOD below); diff images and a JSON/Markdown
     report go to docs/evidence/tikz/.

METHOD (the documented tolerance):
  - Page size must agree within 1 px in each dimension (page = PGF bounding
    box + 2 x border, so this checks the bounding-box computation).
  - A pixel "differs" when any RGB channel differs by more than 64/255.
  - Strict mismatch = differing pixels / ink pixels (ink = pixels that are
    not near-white in either raster).
  - Tolerant mismatch: a pixel of one raster is accepted when some pixel of
    the other raster within a 1 px neighbourhood (3x3) is within 64/255 on
    every channel; counted in both directions, divided by ink pixels. This
    absorbs sub-pixel anti-aliasing and hinting differences (Type 1 hinted
    fonts in pdflatex output vs unhinted CFF in ours) but not geometric
    errors of 1 px (0.48 pt) or more.
  - PASS: size within 1 px AND tolerant mismatch <= 1.0 % of ink pixels.

Usage: compare.py [--fixtures DIR] [--out DIR] [--bin PATH] [NAME ...]
"""
import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile

from PIL import Image, ImageChops, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
CRATE = os.path.dirname(os.path.dirname(HERE))
DPI = 150
THRESH = 64
TOLERANT_PASS = 1.0  # percent of ink pixels


def run(cmd, cwd=None):
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)


def rasterize(pdf, ppm):
    r = run(["gs", "-q", "-dNOPAUSE", "-dBATCH", "-dSAFER", "-sDEVICE=ppmraw",
             f"-r{DPI}", "-dGraphicsAlphaBits=4", "-dTextAlphaBits=4",
             "-dFirstPage=1", "-dLastPage=1", f"-sOutputFile={ppm}", pdf])
    if r.returncode != 0:
        raise RuntimeError(f"gs failed on {pdf}: {r.stderr.strip()[:400]}")
    return Image.open(ppm).convert("RGB")


def channel_bands(img):
    return img.split()


def within(img_a, img_b):
    """Mask (L) of pixels of b that match some pixel of a in a 3x3 window."""
    ok = None
    for ca, cb in zip(img_a.split(), img_b.split()):
        lo = ca.filter(ImageFilter.MinFilter(3))
        hi = ca.filter(ImageFilter.MaxFilter(3))
        # b >= lo - T  <=>  lo - b <= T ; b <= hi + T  <=>  b - hi <= T
        below = ImageChops.subtract(lo, cb)  # clipped at 0
        above = ImageChops.subtract(cb, hi)
        bad = ImageChops.lighter(below, above).point(lambda v: 255 if v > THRESH else 0)
        ok = bad if ok is None else ImageChops.lighter(ok, bad)
    return ok  # 255 = mismatch


def count(mask):
    return mask.histogram()[255]


def compare(ref, ours, diff_png):
    w = min(ref.width, ours.width)
    h = min(ref.height, ours.height)
    a = ref.crop((0, 0, w, h))
    b = ours.crop((0, 0, w, h))
    diff = ImageChops.difference(a, b)
    strict = None
    for c in diff.split():
        m = c.point(lambda v: 255 if v > THRESH else 0)
        strict = m if strict is None else ImageChops.lighter(strict, m)
    ink = None
    for img in (a, b):
        for c in img.split():
            m = c.point(lambda v: 255 if v < 240 else 0)
            ink = m if ink is None else ImageChops.lighter(ink, m)
    tol_ab = within(a, b)
    tol_ba = within(b, a)
    tolerant = ImageChops.lighter(tol_ab, tol_ba)
    ink_px = max(count(ink), 1)
    # Visualisation: reference in grey, tolerant mismatches in red.
    vis = Image.blend(a.convert("L").convert("RGB"), Image.new("RGB", (w, h), "white"), 0.6)
    red = Image.new("RGB", (w, h), (255, 0, 0))
    vis.paste(red, mask=tolerant)
    vis.save(diff_png)
    return {
        "ink_px": ink_px,
        "strict_px": count(strict),
        "strict_pct": round(100.0 * count(strict) / ink_px, 3),
        "tolerant_px": count(tolerant),
        "tolerant_pct": round(100.0 * count(tolerant) / ink_px, 3),
    }


def write_report(out, s):
    lines = [
        "# TikZ oracle comparison (generated by `tools/tikz-oracle/compare.py`)",
        "",
        "pdflatex is the oracle only; the FlashTeX side is `flashtex-tikz-pdf`",
        "(no TeX). Method and tolerance: see the docstring of `compare.py`.",
        "",
        f"- reference: {s['pdflatex']} (standalone class, `border=5pt`, T1 + lmodern)",
        f"- rasteriser: Ghostscript {s['ghostscript']}, {s['dpi']} dpi, 4-bit anti-aliasing",
        f"- pixel threshold: {s['threshold']}/255 per channel; PASS = page size within 1 px"
        f" and tolerant (3x3) mismatch <= {s['tolerant_pass_pct']}% of ink pixels",
        f"- result: **{s['passed']}/{s['total']} pass**",
        "",
        "| fixture | size ref / ours (px) | ink px | strict % | tolerant % | diagnostics | result |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in s["results"]:
        if "error" in r:
            lines.append(f"| {r['fixture']} | | | | | | ERROR: {r['error']} |")
            continue
        lines.append(
            f"| {r['fixture']} | {r['ref_size_px'][0]}x{r['ref_size_px'][1]} / {r['our_size_px'][0]}x{r['our_size_px'][1]} "
            f"| {r['ink_px']} | {r['strict_pct']:.2f} | {r['tolerant_pct']:.2f} | {len(r['diagnostics'])} "
            f"| {'PASS' if r['pass'] else 'FAIL'} |")
    lines += ["", "`diff/<fixture>.png`: the reference in grey with tolerant mismatches in red.", ""]
    with open(os.path.join(out, "README.md"), "w") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fixtures", default=os.path.join(CRATE, "fixtures", "tikz"))
    ap.add_argument("--out", default=os.path.join(CRATE, "docs", "evidence", "tikz"))
    ap.add_argument("--bin", default=os.path.join(CRATE, "target", "release", "flashtex-tikz-pdf"))
    ap.add_argument("--keep", action="store_true", help="keep PDFs and rasters in --out/raw")
    ap.add_argument("names", nargs="*")
    args = ap.parse_args()
    pdflatex = shutil.which("pdflatex")
    if not pdflatex:
        sys.exit("pdflatex (oracle) not found")
    os.makedirs(os.path.join(args.out, "diff"), exist_ok=True)
    fixtures = sorted(f[:-4] for f in os.listdir(args.fixtures) if f.endswith(".tex"))
    if args.names:
        fixtures = [f for f in fixtures if any(n in f for n in args.names)]
    results = []
    for name in fixtures:
        src = os.path.join(args.fixtures, name + ".tex")
        with tempfile.TemporaryDirectory() as tmp:
            shutil.copy(src, os.path.join(tmp, "ref.tex"))
            r = run([pdflatex, "-interaction=batchmode", "-halt-on-error", "ref.tex"], cwd=tmp)
            ref_pdf = os.path.join(tmp, "ref.pdf")
            if r.returncode != 0 or not os.path.exists(ref_pdf):
                results.append({"fixture": name, "error": "pdflatex failed"})
                continue
            our_pdf = os.path.join(tmp, "ours.pdf")
            r = run([args.bin, src, our_pdf])
            diags = [l for l in r.stderr.splitlines() if l.strip()]
            if r.returncode != 0:
                results.append({"fixture": name, "error": "flashtex-tikz-pdf failed", "diagnostics": diags})
                continue
            ref = rasterize(ref_pdf, os.path.join(tmp, "ref.ppm"))
            ours = rasterize(our_pdf, os.path.join(tmp, "ours.ppm"))
            m = compare(ref, ours, os.path.join(args.out, "diff", name + ".png"))
            m.update({
                "fixture": name,
                "ref_size_px": [ref.width, ref.height],
                "our_size_px": [ours.width, ours.height],
                "size_ok": abs(ref.width - ours.width) <= 1 and abs(ref.height - ours.height) <= 1,
                "diagnostics": diags,
            })
            m["pass"] = m["size_ok"] and m["tolerant_pct"] <= TOLERANT_PASS
            if args.keep:
                raw = os.path.join(args.out, "raw")
                os.makedirs(raw, exist_ok=True)
                shutil.copy(ref_pdf, os.path.join(raw, name + ".ref.pdf"))
                shutil.copy(our_pdf, os.path.join(raw, name + ".ours.pdf"))
                ref.save(os.path.join(raw, name + ".ref.png"))
                ours.save(os.path.join(raw, name + ".ours.png"))
            results.append(m)
        res = results[-1]
        if "error" in res:
            print(f"{name:28s} ERROR {res['error']}")
        else:
            print(f"{name:28s} {'PASS' if res['pass'] else 'FAIL'} size {res['ref_size_px']} vs {res['our_size_px']} "
                  f"strict {res['strict_pct']:6.2f}% tolerant {res['tolerant_pct']:6.2f}% diags {len(res['diagnostics'])}")
    passed = sum(1 for r in results if r.get("pass"))
    summary = {
        "dpi": DPI, "threshold": THRESH, "tolerant_pass_pct": TOLERANT_PASS,
        "pdflatex": run([pdflatex, "--version"]).stdout.splitlines()[0],
        "ghostscript": run(["gs", "--version"]).stdout.strip(),
        "passed": passed, "total": len(results), "results": results,
    }
    if not args.names:
        with open(os.path.join(args.out, "results.json"), "w") as f:
            json.dump(summary, f, indent=1)
        write_report(args.out, summary)
    print(f"{passed}/{len(results)} pass")
    return 0 if passed == len(results) else 1


if __name__ == "__main__":
    sys.exit(main())
