(DESIGNSIZE R 10.0)
(COMMENT DESIGNSIZE IS IN POINTS)
(COMMENT OTHER SIZES ARE MULTIPLES OF DESIGNSIZE)
(CHECKSUM O 2215053170)
(BOUNDARYCHAR C B)
(LIGTABLE
   (LABEL C A)
   (KRN C B R -0.125)
   (STOP)
   )
(CHARACTER C A
   (CHARWD R 0.5)
   (COMMENT
      (KRN C B R -0.125)
      )
   )
(CHARACTER C B
   (CHARWD R 0.5)
   )
