(DESIGNSIZE R 10.0)
(COMMENT DESIGNSIZE IS IN POINTS)
(COMMENT OTHER SIZES ARE MULTIPLES OF DESIGNSIZE)
(CHECKSUM O 2215053170)
(BOUNDARYCHAR O 372)
(LIGTABLE
   (LABEL C A)
   (KRN O 372 R -0.125)
   (STOP)
   (LABEL BOUNDARYCHAR)
   (KRN C A R -0.125)
   (STOP)
   )
(CHARACTER C A
   (CHARWD R 0.5)
   (COMMENT
      (KRN O 372 R -0.125)
      )
   )
(CHARACTER C B
   (CHARWD R 0.5)
   )
